### ISSUE TITLE
Test changetip

### ISSUE THREAD

**Issue by spro** [spro/qrtle#1]

**Comment by spro** [comment]
@brynwaldwick 5 seconds of cat on me @changetip 100 bits

**Comment by spro** [comment]
sorry about that here's 10 seconds for delay @brynwaldwick @changetip 200 bits

**Comment by changetip** [comment]
Hi @brynwaldwick, I've delivered a Bitcoin tip worth 200 bits ($0.06) from @spro to your ChangeTip wallet.

**[Learn about ChangeTip](https://www.changetip.com/tip-online/github)**
